### ISSUE TITLE
check-condition failure in `src/idiom8ex.fz`

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion-idioms#65]
```
error 1: *** java.lang.Error: check-condition failed: dev.flang.be.interpreter.ValueWithClazz:clazz:90
Call stack:
((ref ordered_map String i32).entry).val: $FUZION/lib/ordered_map.fz:52:12:
    val => vs[i]
-----------^
(((ref ordered_map String i32).index [ ]).ref @1074496181).call: $FUZION/lib/ordered_map.fz:76:46:
                 .map (i -> sortedEntries[i].val)
---------------------------------------------^
(option i32).map i32: $FUZION/lib/option.fz:89:26:
    option.this ? v T => f v
-------------------------^
(ref ordered_map String i32).index [ ]: $FUZION/lib/ordered_map.fz:76:19:
                 .map (i -> sortedEntries[i].val)
------------------^
ex8.#loop0: src/idiom8ex.fz:13:23:
    say "$s maps to {x[s]}"
----------------------^
ex8: src/idiom8ex.fz:12:3:
  for s in ["one", "two", "three"] do
--^



error 2: java.lang.Error: check-condition failed: dev.flang.be.interpreter.ValueWithClazz:clazz:90
	at dev.flang.util.ANY.check(ANY.java:383)
	at dev.flang.be.interpreter.ValueWithClazz.clazz(ValueWithClazz.java:90)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:319)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:573)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:451)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:648)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:648)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:379)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:227)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:103)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:368)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:727)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```

It works as expected without pre/postconditions enabled.

**Comment by fridis** [comment]
This was fixed by https://github.com/tokiwa-software/fuzion/pull/1426
